### ISSUE TITLE
Ubuntu 22.04 SSL handshake failed

### ISSUE THREAD

**Issue by suoko** [yuezk/GlobalProtect-openconnect#142]
I can't connect with 22.04 due to "SSL handshake failed" error, however I found a way to connect via CLI, you can see how at https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1960268/comments/26

Is there a chance to make this GUI work ?

**Comment by impsik** [comment]
Same problem, i upgraded to 22.04 today.

**Comment by suoko** [comment]
> Same problem, i upgraded to 22.04 today.

Do you know how to pass the cookie to this client ?

**Comment by impsik** [comment]
> > Same problem, i upgraded to 22.04 today.
> 
> Do you know how to pass the cookie to this client ?

Sorry, no. 
I got my VPN working like this:
```
cat <<EOT >> ~/ssl.conf
openssl_conf = openssl_init
[openssl_init]
ssl_conf = ssl_sect
[ssl_sect]
system_default = system_default_sect
[system_default_sect]
Options = UnsafeLegacyRenegotiation
EOT
```

Then i ran:
`OPENSSL_CONF=~/ssl.conf gp-saml-gui -P --gateway example.com`

**Comment by michaelarnauts** [comment]
Some logs that might be interesting:

```
apr 22 16:55:07 michael-Precision-5520 com.yuezk.qt.gpclient.desktop[85360]: 2022-04-22 16:55:07.494 INFO  [85360] [GPClient::doConnect@246] Start connecting...
apr 22 16:55:07 michael-Precision-5520 com.yuezk.qt.gpclient.desktop[85360]: 2022-04-22 16:55:07.494 INFO  [85360] [GPClient::doConnect@262] Start gateway login using the previously saved gateway...
apr 22 16:55:07 michael-Precision-5520 com.yuezk.qt.gpclient.desktop[85360]: 2022-04-22 16:55:07.494 INFO  [85360] [GPClient::gatewayLogin@357] Performing gateway login...
apr 22 16:55:07 michael-Precision-5520 com.yuezk.qt.gpclient.desktop[85360]: 2022-04-22 16:55:07.497 INFO  [85360] [GatewayAuthenticator::authenticate@33] Start gateway authentication...
apr 22 16:55:07 michael-Precision-5520 com.yuezk.qt.gpclient.desktop[85360]: 2022-04-22 16:55:07.497 INFO  [85360] [GatewayAuthenticator::login@46] Trying to login the gateway at https://vpn.xxx.xxx.xx/ssl-vpn/login.esp with prot=https%3A&server=&jnlpReady=jnlpReady&computer=michael-Precision-5520&ok=Login&direct=yes&clientVer=4100&os-version=Ubuntu 22.04 LTS&clientos=Linux&portal-prelogonuserauthcookie=&prelogin-cookie=&ipv6-support=yes&user=&passwd=&portal-userauthcookie=&inputStr=
apr 22 16:55:07 michael-Precision-5520 com.yuezk.qt.gpclient.desktop[85360]: 2022-04-22 16:55:07.541 ERROR [85360] [GatewayAuthenticator::onLoginFinished@58] Failed to login the gateway at https://vpn.xxx.xxx.xx/ssl-vpn/login.esp, SSL handshake failed
apr 22 16:55:07 michael-Precision-5520 com.yuezk.qt.gpclient.desktop[85360]: 2022-04-22 16:55:07.541 INFO  [85360] [GatewayAuthenticator::doAuth@86] Perform the gateway prelogin at https://vpn.xxx.xxx.xx/ssl-vpn/prelogin.esp?tmp=tmp&kerberos-support=yes&ipv6-support=yes&clientVer=4100&clientos=Linux
apr 22 16:55:07 michael-Precision-5520 com.yuezk.qt.gpclient.desktop[85360]: 2022-04-22 16:55:07.573 ERROR [85360] [GatewayAuthenticator::onPreloginFinished@97] Failed to prelogin the gateway at https://vpn.xxx.xxx.xx/ssl-vpn/prelogin.esp?tmp=tmp&kerberos-support=yes&ipv6-support=yes&clientVer=4100&clientos=Linux, SSL handshake failed
apr 22 16:55:07 michael-Precision-5520 com.yuezk.qt.gpclient.desktop[85360]: 2022-04-22 16:55:07.580 INFO  [85360] [PortalAuthenticator::authenticate@33] Preform portal prelogin at https://vpn.xxx.xxx.xx/global-protect/prelogin.esp?tmp=tmp&kerberos-support=yes&ipv6-support=yes&clientVer=4100&clientos=Linux
apr 22 16:55:07 michael-Precision-5520 com.yuezk.qt.gpclient.desktop[85360]: 2022-04-22 16:55:07.612 ERROR [85360] [PortalAuthenticator::onPreloginFinished@44] Error occurred while accessing https://vpn.xxx.xxx.xx/global-protect/prelogin.esp?tmp=tmp&kerberos-support=yes&ipv6-support=yes&clientVer=4100&clientos=Linux, SSL handshake failed
apr 22 16:55:07 michael-Precision-5520 com.yuezk.qt.gpclient.desktop[85360]: 2022-04-22 16:55:07.612 INFO  [85360] [GPClient::onPortalPreloginFail@317] Portal prelogin failed: Error occurred on the portal prelogin interface.
apr 22 16:55:07 michael-Precision-5520 com.yuezk.qt.gpclient.desktop[85360]: 2022-04-22 16:55:07.612 INFO  [85360] [GPClient::tryGatewayLogin@338] Try to preform login on the the gateway interface...
apr 22 16:55:07 michael-Precision-5520 com.yuezk.qt.gpclient.desktop[85360]: 2022-04-22 16:55:07.612 INFO  [85360] [GPClient::setAllGateways@437] Updating all the gateways...
apr 22 16:55:07 michael-Precision-5520 com.yuezk.qt.gpclient.desktop[85360]: 2022-04-22 16:55:07.612 INFO  [85360] [GPClient::populateGatewayMenu@141] Populating the Switch Gateway menu...
apr 22 16:55:07 michael-Precision-5520 com.yuezk.qt.gpclient.desktop[85360]: 2022-04-22 16:55:07.613 INFO  [85360] [GPClient::setCurrentGateway@457] Updating the current gateway to vpn.xxx.xxx.xx
apr 22 16:55:07 michael-Precision-5520 com.yuezk.qt.gpclient.desktop[85360]: 2022-04-22 16:55:07.613 INFO  [85360] [GPClient::populateGatewayMenu@141] Populating the Switch Gateway menu...
apr 22 16:55:07 michael-Precision-5520 com.yuezk.qt.gpclient.desktop[85360]: 2022-04-22 16:55:07.614 INFO  [85360] [GPClient::gatewayLogin@357] Performing gateway login...
apr 22 16:55:07 michael-Precision-5520 com.yuezk.qt.gpclient.desktop[85360]: 2022-04-22 16:55:07.617 INFO  [85360] [GatewayAuthenticator::authenticate@33] Start gateway authentication...
apr 22 16:55:07 michael-Precision-5520 com.yuezk.qt.gpclient.desktop[85360]: 2022-04-22 16:55:07.617 INFO  [85360] [GatewayAuthenticator::login@46] Trying to login the gateway at https://vpn.xxx.xxx.xx/ssl-vpn/login.esp with prot=https%3A&server=&jnlpReady=jnlpReady&computer=michael-Precision-5520&ok=Login&direct=yes&clientVer=4100&os-version=Ubuntu 22.04 LTS&clientos=Linux&portal-prelogonuserauthcookie=&prelogin-cookie=&ipv6-support=yes&user=&passwd=&portal-userauthcookie=&inputStr=
apr 22 16:55:07 michael-Precision-5520 com.yuezk.qt.gpclient.desktop[85360]: 2022-04-22 16:55:07.663 ERROR [85360] [GatewayAuthenticator::onLoginFinished@58] Failed to login the gateway at https://vpn.xxx.xxx.xx/ssl-vpn/login.esp, SSL handshake failed
apr 22 16:55:07 michael-Precision-5520 com.yuezk.qt.gpclient.desktop[85360]: 2022-04-22 16:55:07.663 INFO  [85360] [GatewayAuthenticator::doAuth@86] Perform the gateway prelogin at https://vpn.xxx.xxx.xx/ssl-vpn/prelogin.esp?tmp=tmp&kerberos-support=yes&ipv6-support=yes&clientVer=4100&clientos=Linux
apr 22 16:55:07 michael-Precision-5520 com.yuezk.qt.gpclient.desktop[85360]: 2022-04-22 16:55:07.694 ERROR [85360] [GatewayAuthenticator::onPreloginFinished@97] Failed to prelogin the gateway at https://vpn.xxx.xxx.xx/ssl-vpn/prelogin.esp?tmp=tmp&kerberos-support=yes&ipv6-support=yes&clientVer=4100&clientos=Linux, SSL handshake failed

```

**Comment by michaelarnauts** [comment]
It might be related, but I would assume that connecting trough the cli also won't work then.

**Comment by michaelarnauts** [comment]
For a system-wide change, so you can use the GUI again.

Edit file `/etc/ssl/openssl.cnf` as root, and add the lines between the comments as indicated below.

```
[openssl_init]
providers = provider_sect

# Added to disable secure renegotiation
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
Options = UnsafeLegacyRenegotiation
# End added to disable secure renegotiation
```

Shutdown the GUI and restart it. You should be able to connect again.

**Comment by onemanbucket** [comment]
Rather than pinning the legacy (unsafe) behaviour system-wide, it's better if the client does it until the vendor has fixed it upstream.

See #146

**Comment by yuezk** [comment]
Fixed in 1.4.2.

**Comment by anshah1216** [comment]
I updated ssl.conf and set OPENSSL_CONF and I'm still getting the following:
![Uploading Screen Shot 2022-12-12 at 4.46.24 PM.png…]()
I'm testing on Ubuntu 22.04 and seeing this when trying to connect to a portal configured with Microsoft Azure SAML configuration with the GP embedded browser. 
Okta works on embedded browser and default browser works.

**Comment by Godzshaka** [comment]
The error is caused by newer versions of Linux that utilize SSL 3, which is disabled on the embedded browser. The workaround suggested is to utilize the default system browser for SAML authentication.

Procedure to fix it:

    Open terminal and change the directory to /opt/paloaltonetworks/globalprotect

cd /opt/paloaltonetworks/globalprotect

    Open pangps.xml file.

sudo vi pangps.xml

    Add the line below under <Settings> 

<default-browser>yes</default-browser>

Save the changes and reboot the machine.

After reboot when you enter GP Portal Address in GP UI and click Connect, GP will start using your system default browser instead of embedded webview.
