### ISSUE TITLE
Not working after update to v2.0.0

### ISSUE THREAD

**Issue by rednag** [yuezk/GlobalProtect-openconnect#338]
**Describe the bug**
Trying to connect to our portal and I'm getting the following error

Connection Failed
error sending request for url (https://...): error trying to connect: dns error:  failed to lookup address information: Name or service not known

**Expected behavior**
Connecting to the GP portal.

**Screenshots**

**Logs**
```
[2024-03-25T07:10:05Z INFO  gpgui::handlers::subscription] Sending the init event to client: mainxxx\.com
[2024-03-25T07:10:05Z INFO  gpgui::handlers::subscription] Sent the init event to client: main
[2024-03-25T07:10:06Z WARN  gpapi::utils::window] Failed to raise window: Failed to raise window: GlobalProtect
[2024-03-25T07:10:08Z INFO  gpgui::portal_connector] Connecting to the portal: p**********m...
[2024-03-25T07:10:08Z INFO  gpgui::portal_connector] Trying to connect the gateway directly...
[2024-03-25T07:10:08Z INFO  gpgui::portal_connector] Gateway prelogin, gateway: g**********m...
[2024-03-25T07:10:08Z INFO  gpapi::portal::prelogin] Prelogin with user_agent: PAN GlobalProtect/6.0.1-19 (Linux Ubuntu 22.04.4 LTS)
[2024-03-25T07:10:08Z INFO  gpgui::portal_connector] Failed to connect the gateway directly: error sending request for url (https://gpintgw-yyy.xxx\.com/ssl-vpn/prelogin.esp): error trying to connect: dns error: failed to lookup address information: Name or service not known
[2024-03-25T07:10:08Z INFO  gpgui::portal_connector] Trying to connect portal with cached credential...
[2024-03-25T07:10:08Z INFO  gpgui::portal_connector] Fetching the portal config...
[2024-03-25T07:10:08Z INFO  gpapi::portal::config] Portal config, user_agent: PAN GlobalProtect/6.0.1-19 (Linux Ubuntu 22.04.4 LTS)
[2024-03-25T07:10:08Z INFO  gpgui::portal_connector] Retrieved 2 gateway(s) from the portal, updating...
[2024-03-25T07:10:08Z INFO  gpgui::portal_connector] Performing gateway login, gateway: g**********m...
[2024-03-25T07:10:08Z INFO  gpapi::gateway::login] Gateway login, user_agent: PAN GlobalProtect/6.0.1-19 (Linux Ubuntu 22.04.4 LTS)
[2024-03-25T07:10:08Z INFO  gpgui::portal_connector] Failed to connect portal with cached credential: error sending request for url (https://gpintgw-yyy.xxx\.com/ssl-vpn/login.esp): error trying to connect: dns error: failed to lookup address information: Name or service not known
[2024-03-25T07:10:08Z INFO  gpgui::portal_connector] Trying to connect the portal with prelogin...
[2024-03-25T07:10:08Z INFO  gpgui::portal_connector] Performing portal prelogin...
[2024-03-25T07:10:08Z INFO  gpapi::portal::prelogin] Prelogin with user_agent: PAN GlobalProtect/6.0.1-19 (Linux Ubuntu 22.04.4 LTS)
[2024-03-25T07:10:08Z INFO  gpgui::portal_connector] Authenticating portal...
[2024-03-25T07:10:08Z INFO  gpgui::portal_connector] Launching SAML authentication...
[2024-03-25T07:10:08Z INFO  gpauth::cli] gpauth started: 2.1.0 (2024-03-10)
[2024-03-25T07:10:08Z INFO  gpauth::auth_window] Open auth window, user_agent: PAN GlobalProtect/6.0.1-19 (Linux Ubuntu 22.04.4 LTS)
[2024-03-25T07:10:08Z INFO  gpauth::auth_window] Auth window user agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15
[2024-03-25T07:10:08Z INFO  gpauth::auth_window] Load the SAML request as URI...
[2024-03-25T07:10:09Z INFO  gpauth::auth_window] Loaded uri: https://l**********m/624cb905-2323-41e4-90b9-e768cf22851a/saml2?SAMLRequest=l**********%3D&RelayState=H**********%3D
[2024-03-25T07:10:09Z INFO  gpauth::auth_window] Trying to read auth data from response headers...
[2024-03-25T07:10:09Z INFO  gpauth::auth_window] No saml-auth-status header found
[2024-03-25T07:10:09Z INFO  gpauth::auth_window] No auth data found in headers, trying to read from body...
[2024-03-25T07:10:09Z INFO  gpauth::auth_window] No auth data found in HTML
[2024-03-25T07:10:09Z INFO  gpauth::auth_window] No auth data found, it may not be the /SAML20/SP/ACS endpoint
[2024-03-25T07:10:09Z INFO  gpauth::auth_window] Raise window in 1 second(s)
[2024-03-25T07:10:09Z INFO  gpauth::auth_window] Raise window cancelled
[2024-03-25T07:10:09Z INFO  gpauth::auth_window] Loaded uri: https://p**********m/SAML20/SP/ACS
[2024-03-25T07:10:09Z INFO  gpauth::auth_window] Trying to read auth data from response headers...
[2024-03-25T07:10:09Z INFO  gpauth::auth_window] Got auth data from headers
[2024-03-25T07:10:09Z INFO  gpgui::portal_connector] Fetching the portal config...
[2024-03-25T07:10:09Z INFO  gpapi::portal::config] Portal config, user_agent: PAN GlobalProtect/6.0.1-19 (Linux Ubuntu 22.04.4 LTS)
[2024-03-25T07:10:10Z INFO  gpgui::portal_connector] Retrieved 2 gateway(s) from the portal, updating...
[2024-03-25T07:10:10Z INFO  gpgui::portal_connector] Performing gateway login, gateway: g**********m...
[2024-03-25T07:10:10Z INFO  gpapi::gateway::login] Gateway login, user_agent: PAN GlobalProtect/6.0.1-19 (Linux Ubuntu 22.04.4 LTS)
[2024-03-25T07:10:10Z INFO  gpgui::portal_connector] Gateway login failed: error sending request for url (https://gpintgw-yyy.xxx\.com/ssl-vpn/login.esp): error trying to connect: dns error: failed to lookup address information: Name or service not known
[2024-03-25T07:10:10Z INFO  gpgui::portal_connector] Gateway prelogin, gateway: g**********m...
[2024-03-25T07:10:10Z INFO  gpapi::portal::prelogin] Prelogin with user_agent: PAN GlobalProtect/6.0.1-19 (Linux Ubuntu 22.04.4 LTS)
[2024-03-25T07:10:10Z INFO  gpgui::portal_connector] Failed to connect the portal with prelogin: error sending request for url (https://gpintgw-yyy.xxx\.com/ssl-vpn/prelogin.esp): error trying to connect: dns error: failed to lookup address information: Name or service not known
[2024-03-25T07:10:10Z WARN  gpgui::portal_connector] Failed to connect to the portal: error sending request for url (https://gpintgw-yyy.xxx\.com/ssl-vpn/prelogin.esp): error trying to connect: dns error: failed to lookup address information: Name or service not known
```

**Environment:**
 - OS: Ubuntu 22.04
 - Desktop Environment: GNOME
 - user    3883  0.0  0.0 241356  7100 ?        Sl   Mär23   0:00 /usr/bin/gnome-keyring-daemon --daemonize --login
 - Is remote SSH? No

**Additional context**
The free to use version worked out of the box and now I have a demo version which is not working?

**Comment by rednag** [comment]
Same issue with v2.1.0

**Comment by rednag** [comment]
Swiched back to the free version 1.4.8 - and everything works fine.

**Comment by yuezk** [comment]
@rednag Thanks for you feedback. Looks like the gateways got from the portal config is not accessible (`failed to lookup address information: Name or service not known`), so it cannot connect. But the portal address can be treated as a gateway and can be connected as you said the old client works.

The old client works because it will try to use the portal as the gateway when you click the Connect button. The new client has a similar logic that it will try to connect the portal as the gateway when some special errors occur, but not include the error you encountered. It should work if I add the DNS error to the special error set.

**Comment by yuezk** [comment]
@rednag Should be fixed in `2.1.1`.

**Comment by picture-vision** [comment]
@yuezk 
Just installed the latest release 2.1.1 and still get a similar error: 

```
[2024-03-28T22:11:27Z INFO  gpgui::portal_connector] Gateway login failed: Gateway error: error sending request for url (https://**_<vpninternal>.<internal>.com_**/ssl-vpn/login.esp): error trying to connect: dns error:
failed to lookup address information: Temporary failure in name resolution
``` 
(The previous release 2.1.0 was working until approx 2 weeks ago. At this point an update to the PaloAlto Windows Clients has been rolled out)

**Comment by yuezk** [comment]
Hi @picture-vision, can you please send me the full log, so I can investigate it further?

**Comment by yuezk** [comment]
Hi @picture-vision, I found a flaw in the code, please upgrade to 2.1.2, it can fix your problem hopefully.

**Comment by picture-vision** [comment]
Hi @yuezk, it is working now. Thanks a lot for the quick response. Great tool!

**Comment by rednag** [comment]
Hi yuezk,

I've now upgrade to 2.1.4 still not working!

**Comment by yuezk** [comment]
Hi @rednag can you provide the logs so I can investigate? Thanks.
